stages:
  # Stage 1: Download and prepare the raw data
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - data/raw/creditcard.csv

  # Stage 2: Clean and preprocess the data
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw/creditcard.csv
    outs:
      - data/processed/X_train.csv
      - data/processed/y_train.csv
      - data/processed/X_test.csv
      - data/processed/y_test.csv
      - data/processed/scaler.pkl

  # Stage 3: Train machine learning models
  model_training:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - data/processed/X_train.csv
      - data/processed/y_train.csv
      - data/processed/X_test.csv
      - data/processed/y_test.csv
    outs:
      - models/logistic_regression_model.pkl
      - models/random_forest_model.pkl
      - visualizations/results.pkl
      - visualizations/model_results.csv
      - visualizations/model_comparison.png

  # Stage 4: Evaluate model performance
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - models/logistic_regression_model.pkl
      - models/random_forest_model.pkl
      - data/processed/X_test.csv
      - data/processed/y_test.csv
    outs:
      - visualizations/detailed_evaluation.png
      - visualizations/evaluation_summary.json
      - models/detailed_evaluation.pkl